---
# Install latest Oracle Java Jdk 8

- name: ensure required packages are installed for Java 8
  apt:
   name: python-software-properties
   state: latest

- name: Add Java repository to sources
  apt_repository:
    repo: 'ppa:webupd8team/java'
    update_cache: yes

- name: Autoaccept license for Java
  debconf:
   name: 'oracle-java8-installer'
   question: 'shared/accepted-oracle-license-v1-1'
   value: 'true'
   vtype: 'select'

- name: Install Java 8
  apt:
   name: oracle-java8-installer
   state: latest
