---
# Install latest Oracle Java Jdk 7 and Jdk 8
#############################################

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: ensure required packages are installed for ppa repositories and for debconf
  apt:
   name:
    - python-software-properties
    - debconf
    - debconf-utils
   state: latest
  become: yes

- name: Add Java repository to sources list
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes
  become: yes

- name: Autoaccept license for Java versions defined in playbook
  debconf: name="oracle-{{item}}-installer" question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  with_items: "{{javaversions}}"
  become: yes

- name: Install Oracle java versions defined in the playbook
  apt: name="oracle-{{item}}-installer" state=latest
  with_items: "{{javaversions}}"
  become: yes


- name: Add JAVA UTF-8 Environment Variable
  lineinfile:
    dest: /etc/environment
    line: JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF-8"
  become: yes
