---
# Install Python, Git, mosh, tmux, byobu,vim, subversion, docker, docker compose


# this section for docker prerequisites and adding docker repository
####################################################################

- name: Install apt-transport-https for apt to be able to use repository over https
  apt: name=apt-transport-https state=present
  become: yes

- name: Install Common CA certificates
  apt: name=ca-certificates state=present
  become: yes

- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
  become: yes

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename|lower }} main
    update_cache: yes
  become: yes

####################################################################
####################################################################

- name: Install Python, Git, mosh, tmux, byobu,vim, subversion, docker, docker compose
  apt:
   name:
    - python
    - git
    - mosh
    - tmux
    - byobu
    - vim
    - subversion
    - docker-engine
    - docker-compose
   state: latest
  become: yes

#- name: Set the open files per process limit (system wide)
#  sysctl: name=fs.file-max value={{ nofile_limit }} state=present
#
#- name: Set the open files per process limit
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: ^root hard nofile
#    line: root hard nofile {{ nofile_limit }}
#
#- name: Set the memory limit
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: ^root hard memlock
#    line: root hard memlock {{ memlock_limit }}
#
#- name: Set the no of process limit
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: ^root hard nproc
#    line: root hard nproc {{ nproc_limit }}
#
#- name: Set the address space limit
#  lineinfile:
#    dest: /etc/security/limits.conf
#    regexp: ^root hard as
#    line: root hard as {{ addrspace_limit }}

#- name: Add JAVA UTF-8 Environment Variable
#  lineinfile:
#    dest: /etc/environment
#    line:
#  become: yes
#
#LC_ALL=en_US.UTF-8
#LANG=en_US.UTF-8
#LC_CTYPE=en_US.UTF-8
