---

##################################################################################
#     Common role for installing common packages and set locale and ulimits      #
##################################################################################

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  become: yes

##################################################################################
#       this section for docker prerequisites and adding docker repository       #
##################################################################################

- name: Install apt-transport-https for apt to be able to use repository over https
  apt: name=apt-transport-https state=present
  become: yes

- name: Install Common CA certificates
  apt: name=ca-certificates state=present
  become: yes

- name: Add Docker repository key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
  become: yes

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ ansible_lsb.id|lower }}-{{ ansible_lsb.codename|lower }} main
    update_cache: yes
  become: yes

##################################################################################
# Install Python, Git, mosh, tmux, byobu,vim, subversion, docker, docker compose #
##################################################################################

- name: Install Python, Git, mosh, tmux, byobu,vim, subversion, docker, docker compose
  apt:
   name:
    - python
    - git
    - mosh
    - tmux
    - byobu
    - vim
    - subversion
    - docker-engine
    - docker-compose
   state: latest
  become: yes

##################################################################################
#                                   Set ulimits                                  #
##################################################################################

- name: Configure pam.d/common-session to enable limits at login
  lineinfile:
   dest: /etc/pam.d/common-session
   line: session required pam_limits.so
  become: yes

- name: Configure pam.d/common-session-noninteractive to enable limits at login
  lineinfile:
   dest: /etc/pam.d/common-session-noninteractive
   line: session required pam_limits.so
  become: yes

- name: Set ulimits "memlock" - max locked-in-memory address space (KB)
  pam_limits: domain=root limit_type='-' limit_item=memlock value={{memlock_limit}}
  become: yes

- name: Set ulimits "nofile" - max number of open files
  pam_limits: domain=root limit_type='-' limit_item=nofile value={{nofile_limit}}
  become: yes

- name: Set ulimits "nproc" - max number of processes
  pam_limits: domain=root limit_type='-' limit_item=nproc value={{nproc_limit}}
  become: yes

- name: Set ulimits "as" - address space limit (KB)
  pam_limits: domain=root limit_type='-' limit_item=as value={{addrspace_limit}}
  become: yes

##################################################################################
#                                Stetting locale                                 #
##################################################################################

- name: Generate locale
  locale_gen: name=en_US.UTF-8 state=present
  become: yes

- name: Set locale "en_US.UTF-8"
  template: src=locale.j2 dest=/etc/default/locale
  become: yes

- name: Attach to last session or create new tmux at login
  lineinfile:
   dest: /home/abdo/.bashrc
   line: /usr/bin/tmux attach || /usr/bin/tmux new
  become: yes
  tags: common
