---

##################################################################################
#                           tasks file for time_sync                             #
##################################################################################

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Ensure NTP daemon (for time synchronization) is installed.
  apt: name=ntp state=present
  become: yes

- name: Set timezone to time_zone_config
  timezone:
    name: "{{time_zone_config}}"
  become: yes

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root mode=0644
  notify:
   - restart ntp


